services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Efata\Bundle\SongbookApiBundle\:
        resource: '../../src/Efata/Bundle/SongbookApiBundle/*'
        exclude: '../../src/Efata/Bundle/SongbookApiBundle/Db/{*File.php, DbUpdateException.php}'