-- MySQL Script generated by MySQL Workbench
-- Št 19. júl 2018, 19:05:28 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `songbook_song_key`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `songbook_song_key` (
  `id_song_key` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sign` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id_song_key`),
  UNIQUE INDEX `index2` (`sign` ASC))
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `songbook_song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `songbook_song` (
  `id_song` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_song_key` INT UNSIGNED NOT NULL,
  `tempo` TINYINT NULL,
  `version` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `modified_at` DATETIME NOT NULL DEFAULT NOW(),
  `published_at` DATETIME NOT NULL,
  PRIMARY KEY (`id_song`),
  INDEX `fk_songbook_song_1_idx` (`id_song_key` ASC),
  CONSTRAINT `fk_songbook_song_1`
  FOREIGN KEY (`id_song_key`)
  REFERENCES `songbook_song_key` (`id_song_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `songbook_author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `songbook_author` (
  `id_author` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(64) NOT NULL,
  `slug` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id_author`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC),
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC))
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `songbook_author_has_song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `songbook_author_has_song` (
  `id_author` INT UNSIGNED NOT NULL,
  `id_song` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_author`, `id_song`),
  INDEX `fk_songbook_author_has_songbook_song_songbook_song1_idx` (`id_song` ASC),
  INDEX `fk_songbook_author_has_songbook_song_songbook_author_idx` (`id_author` ASC),
  CONSTRAINT `fk_songbook_author_has_songbook_song_songbook_author`
  FOREIGN KEY (`id_author`)
  REFERENCES `songbook_author` (`id_author`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_songbook_author_has_songbook_song_songbook_song1`
  FOREIGN KEY (`id_song`)
  REFERENCES `songbook_song` (`id_song`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `songbook_language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `songbook_language` (
  `id_language` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `slug` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id_language`),
  UNIQUE INDEX `index2` (`title` ASC),
  UNIQUE INDEX `index3` (`slug` ASC))
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `songbook_title`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `songbook_song_title` (
  `id_title` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_song` INT UNSIGNED NOT NULL,
  `id_language` INT UNSIGNED NOT NULL,
  `title` VARCHAR(64) NOT NULL,
  `slug` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id_title`),
  INDEX `fk_songbook_title_1_idx` (`id_song` ASC),
  UNIQUE INDEX `index3` (`id_song` ASC, `title` ASC, `id_language` ASC),
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC),
  INDEX `fk_songbook_title_2_idx` (`id_language` ASC),
  CONSTRAINT `fk_songbook_title_1`
  FOREIGN KEY (`id_song`)
  REFERENCES `songbook_song` (`id_song`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_songbook_title_2`
  FOREIGN KEY (`id_language`)
  REFERENCES `songbook_language` (`id_language`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `songbook_song_verse_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `songbook_song_verse_type` (
  `id_song_verse_type` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(24) NOT NULL,
  `slug` VARCHAR(24) NOT NULL,
  PRIMARY KEY (`id_song_verse_type`),
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC))
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `songbook_song_verse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `songbook_song_verse` (
  `id_song_verse` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_song` INT UNSIGNED NOT NULL,
  `id_song_verse_type` INT UNSIGNED NOT NULL,
  `order` TINYINT NULL,
  PRIMARY KEY (`id_song_verse`),
  INDEX `fk_songbook_song_verse_1_idx` (`id_song` ASC),
  INDEX `fk_songbook_song_verse_2_idx` (`id_song_verse_type` ASC),
  CONSTRAINT `fk_songbook_song_verse_1`
  FOREIGN KEY (`id_song`)
  REFERENCES `songbook_song` (`id_song`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_songbook_song_verse_2`
  FOREIGN KEY (`id_song_verse_type`)
  REFERENCES `songbook_song_verse_type` (`id_song_verse_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `songbook_song_verse_lyrics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `songbook_song_verse_lyrics` (
  `id_song_verse_lyrics` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_song_verse` INT UNSIGNED NOT NULL,
  `id_language` INT UNSIGNED NOT NULL,
  `lyrics` TEXT NOT NULL,
  PRIMARY KEY (`id_song_verse_lyrics`),
  INDEX `fk_songbook_song_verse_lyrics_1_idx` (`id_song_verse` ASC),
  INDEX `fk_songbook_song_verse_lyrics_2_idx` (`id_language` ASC),
  CONSTRAINT `fk_songbook_song_verse_lyrics_1`
  FOREIGN KEY (`id_song_verse`)
  REFERENCES `songbook_song_verse` (`id_song_verse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_songbook_song_verse_lyrics_2`
  FOREIGN KEY (`id_language`)
  REFERENCES `songbook_language` (`id_language`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `songbook_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `songbook_tag` (
  `id_tag` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `slug` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tag`),
  UNIQUE INDEX `index2` (`title` ASC),
  UNIQUE INDEX `index3` (`slug` ASC))
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `songbook_song_has_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `songbook_song_has_tag` (
  `id_song` INT UNSIGNED NOT NULL,
  `id_tag` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_song`, `id_tag`),
  INDEX `fk_songbook_tag_has_songbook_song_songbook_song1_idx` (`id_song` ASC),
  INDEX `fk_songbook_tag_has_songbook_song_songbook_tag1_idx` (`id_tag` ASC),
  CONSTRAINT `fk_songbook_tag_has_songbook_song_songbook_tag1`
  FOREIGN KEY (`id_tag`)
  REFERENCES `songbook_tag` (`id_tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_songbook_tag_has_songbook_song_songbook_song1`
  FOREIGN KEY (`id_song`)
  REFERENCES `songbook_song` (`id_song`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `songbook_song_version`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `songbook_song_version` (
  `id_song_version` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_song_version`))
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `songbook_song_version_verse_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `songbook_song_version_verse_order` (
  `id_song_version_verse_order` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_song_version` INT UNSIGNED NOT NULL,
  `id_verse` INT UNSIGNED NOT NULL,
  `order` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_song_version_verse_order`),
  INDEX `fk_songbook_song_version_verse_order_1_idx` (`id_song_version` ASC),
  INDEX `fk_songbook_song_version_verse_order_2_idx` (`id_verse` ASC),
  UNIQUE INDEX `index4` (`id_song_version` ASC, `order` ASC),
  CONSTRAINT `fk_songbook_song_version_verse_order_1`
  FOREIGN KEY (`id_song_version`)
  REFERENCES `songbook_song_version` (`id_song_version`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_songbook_song_version_verse_order_2`
  FOREIGN KEY (`id_verse`)
  REFERENCES `songbook_song_verse` (`id_song_verse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `songbook_song_record_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `songbook_song_record_type` (
  `id_song_record_type` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_song_record_type`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC))
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `songbook_song_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `songbook_song_record` (
  `id_song_record` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_song` INT UNSIGNED NOT NULL,
  `id_song_record_type` INT UNSIGNED NOT NULL,
  `url` VARCHAR(256) NOT NULL,
  `note` VARCHAR(64) NULL,
  PRIMARY KEY (`id_song_record`),
  INDEX `fk_songbook_song_record_1_idx` (`id_song` ASC),
  INDEX `fk_songbook_song_record_2_idx` (`id_song_record_type` ASC),
  CONSTRAINT `fk_songbook_song_record_1`
  FOREIGN KEY (`id_song`)
  REFERENCES `songbook_song` (`id_song`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_songbook_song_record_2`
  FOREIGN KEY (`id_song_record_type`)
  REFERENCES `songbook_song_record_type` (`id_song_record_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `songbook_song_time_signature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `songbook_song_time_signature` (
  `id_song_time_signature` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `upper_number` TINYINT UNSIGNED NOT NULL,
  `lower_number` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_song_time_signature`))
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `songbook_song_has_time_signature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `songbook_song_has_time_signature` (
  `id_song` INT UNSIGNED NOT NULL,
  `id_song_time_signature` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_song`, `id_song_time_signature`),
  INDEX `fk_songbook_song_has_songbook_song_time_signature_songbook__idx` (`id_song_time_signature` ASC),
  INDEX `fk_songbook_song_has_songbook_song_time_signature_songbook__idx1` (`id_song` ASC),
  CONSTRAINT `fk_songbook_song_has_songbook_song_time_signature_songbook_so1`
  FOREIGN KEY (`id_song`)
  REFERENCES `songbook_song` (`id_song`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_songbook_song_has_songbook_song_time_signature_songbook_so2`
  FOREIGN KEY (`id_song_time_signature`)
  REFERENCES `songbook_song_time_signature` (`id_song_time_signature`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `songbook_song_note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `songbook_song_note` (
  `id_song_note` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `note` TEXT NOT NULL,
  PRIMARY KEY (`id_song_note`))
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `songbook_song_has_note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `songbook_song_has_note` (
  `id_song` INT UNSIGNED NOT NULL,
  `id_song_note` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_song`, `id_song_note`),
  INDEX `fk_songbook_song_has_songbook_song_note_songbook_song_note1_idx` (`id_song_note` ASC),
  INDEX `fk_songbook_song_has_songbook_song_note_songbook_song1_idx` (`id_song` ASC),
  CONSTRAINT `fk_songbook_song_has_songbook_song_note_songbook_song1`
  FOREIGN KEY (`id_song`)
  REFERENCES `songbook_song` (`id_song`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_songbook_song_has_songbook_song_note_songbook_song_note1`
  FOREIGN KEY (`id_song_note`)
  REFERENCES `songbook_song_note` (`id_song_note`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
